defaults:
    - model: resnet18
    - dataset@train_dataset: cifar10
    - dataset@test_dataset: cifar10
    - dataset@trust_dataset: null
    - distribution: dirichlet
    - model_trainer: cifar10
    - federated_method: fedavg
    - client_selector: uniform
    - manager: client_selection
    - losses@loss: ce
    - optimizer: adam
    - preaggregator: null
    - _self_

random_state: 42
single_run_dir: ${hydra:run.dir}

training_params:
    batch_size: 256
    num_workers: 4
    device: "cuda"
    device_ids: [0]

federated_params:
    amount_of_clients: 10
    client_subset_size: 5 # How many clients do we select in each round
    communication_rounds: 200
    local_epochs: 1
    client_train_val_prop: 0.2
    print_client_metrics: True
    server_saving_metrics: ["loss"] # "loss", "Specificity", "Sensitivity", "G-mean", "f1-score", "fbeta2-score", "ROC-AUC", "AP", "Precision (PPV)", "NPV"
    server_saving_agg: "uniform" # weighted
    clients_attack_types: "no_attack" # label_flip, sign_flip, random_grad, alie, ipm; Can be mixed with a list ['label_flip', 'sign_flip']
    prop_attack_clients: 0.0 # Must be in accordance with `clients_attack_types`.
    attack_scheme: "no_attack" # constant, random_rounds, random_clients, random_rounds_random_clients
    prop_attack_rounds: 0.0
